CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.REGION_SILVER (
    R_NAME VARCHAR,
    R_COMMENT VARCHAR
);

MERGE INTO RL_SQL_DEMO.SILVER.REGION_SILVER AS target
USING SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION AS source
ON target.R_NAME = source.R_NAME
WHEN NOT MATCHED THEN
    INSERT (R_NAME, R_COMMENT)
    VALUES (source.R_NAME, source.R_COMMENT)
WHEN MATCHED THEN
    UPDATE SET
        R_NAME = source.R_NAME,
        R_COMMENT = source.R_COMMENT;
