-- Create SILVER orders table with cleaner column names
CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.ORDERS_SILVER (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_STATUS VARCHAR,
    TOTAL_PRICE NUMBER,
    ORDER_DATE DATE,
    ORDER_PRIORITY VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP
);

-- Merge from BRONZE to SILVER
MERGE INTO RL_SQL_DEMO.SILVER.ORDERS_SILVER AS TGT
USING RL_SQL_DEMO.BRONZE.ORDERS_BRONZE AS SRC
ON TGT.ORDER_ID = SRC.O_ORDERKEY
WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_ID = SRC.O_CUSTKEY,
        ORDER_STATUS = SRC.O_ORDERSTATUS,
        TOTAL_PRICE = SRC.O_TOTALPRICE,
        ORDER_DATE = SRC.O_ORDERDATE,
        ORDER_PRIORITY = SRC.O_ORDERPRIORITY,
        LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, TOTAL_PRICE, ORDER_DATE, ORDER_PRIORITY, LOAD_TIMESTAMP)
    VALUES (SRC.O_ORDERKEY, SRC.O_CUSTKEY, SRC.O_ORDERSTATUS, SRC.O_TOTALPRICE, SRC.O_ORDERDATE, SRC.O_ORDERPRIORITY, CURRENT_TIMESTAMP());

