-- Create SILVER part table with cleaner column names
CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.PART_SILVER (
    PART_ID NUMBER,
    PART_NAME VARCHAR,
    PART_BRAND VARCHAR,
    PART_TYPE VARCHAR,
    PART_SIZE NUMBER,
    RETAIL_PRICE NUMBER,
    LOAD_TIMESTAMP TIMESTAMP
);

-- Merge from BRONZE to SILVER
MERGE INTO RL_SQL_DEMO.SILVER.PART_SILVER AS TGT
USING RL_SQL_DEMO.BRONZE.PART_BRONZE AS SRC
ON TGT.PART_ID = SRC.P_PARTKEY
WHEN MATCHED THEN
    UPDATE SET
        PART_NAME = SRC.P_NAME,
        PART_BRAND = SRC.P_BRAND,
        PART_TYPE = SRC.P_TYPE,
        PART_SIZE = SRC.P_SIZE,
        RETAIL_PRICE = SRC.P_RETAILPRICE,
        LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (PART_ID, PART_NAME, PART_BRAND, PART_TYPE, PART_SIZE, RETAIL_PRICE, LOAD_TIMESTAMP)
    VALUES (SRC.P_PARTKEY, SRC.P_NAME, SRC.P_BRAND, SRC.P_TYPE, SRC.P_SIZE, SRC.P_RETAILPRICE, CURRENT_TIMESTAMP());

