CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.REGION_SILVER(
    R_NAME VARCHAR,
    R_COMMENT VARCHAR
);

MERGE INTO RL_SQL_DEMO.SILVER.REGION_SILVER AS target
USING (
    SELECT R_NAME, R_COMMENT 
    FROM RL_SQL_DEMO.BRONZE.REGION_BRONZE
) AS source
ON target.R_NAME = source.R_NAME
WHEN MATCHED THEN
    UPDATE SET 
        target.R_NAME = source.R_NAME,
        target.R_COMMENT = source.R_COMMENT
WHEN NOT MATCHED THEN
    INSERT (R_NAME, R_COMMENT)
    VALUES (source.R_NAME, source.R_COMMENT);

