-- Create SILVER customer table with cleaner column names
CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.CUSTOMER_SILVER (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    PHONE VARCHAR,
    ACCOUNT_BALANCE NUMBER,
    MARKET_SEGMENT VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP
);

-- Merge from BRONZE to SILVER
MERGE INTO RL_SQL_DEMO.SILVER.CUSTOMER_SILVER AS TGT
USING RL_SQL_DEMO.BRONZE.CUSTOMER_BRONZE AS SRC
ON TGT.CUSTOMER_ID = SRC.C_CUSTKEY
WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_NAME = SRC.C_NAME,
        PHONE = SRC.C_PHONE,
        ACCOUNT_BALANCE = SRC.C_ACCTBAL,
        MARKET_SEGMENT = SRC.C_MKTSEGMENT,
        LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (CUSTOMER_ID, CUSTOMER_NAME, PHONE, ACCOUNT_BALANCE, MARKET_SEGMENT, LOAD_TIMESTAMP)
    VALUES (SRC.C_CUSTKEY, SRC.C_NAME, SRC.C_PHONE, SRC.C_ACCTBAL, SRC.C_MKTSEGMENT, CURRENT_TIMESTAMP());

