CREATE TABLE IF NOT EXISTS RL_SQL_DEMO.SILVER.PART_SILVER (
    R_NAME VARCHAR,
    R_COMMENT VARCHAR
);

MERGE INTO RL_SQL_DEMO.SILVER.PART_SILVER AS target
USING SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART AS source
ON target.R_NAME = source.P_NAME
WHEN MATCHED THEN
    UPDATE SET 
        target.R_NAME = source.P_NAME,
        target.R_COMMENT = source.P_COMMENT
WHEN NOT MATCHED THEN
    INSERT (R_NAME, R_COMMENT)
    VALUES (source.P_NAME, source.P_COMMENT);

