-- create the custom role and grant to SYSADMIN
USE ROLE USERADMIN;
CREATE ROLE RL_DATA_ENGINEER;
GRANT ROLE RL_DATA_ENGINEER TO ROLE SYSADMIN;

-- create the database and grant ownership to the custom role
USE ROLE SYSADMIN;
CREATE DATABASE RL_SQL_DEMO;
GRANT OWNERSHIP ON DATABASE RL_SQL_DEMO TO ROLE RL_DATA_ENGINEER;

-- create the warehouse and grant usage to the custom role
CREATE WAREHOUSE RL_DATA_ENGINEER_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE RL_DATA_ENGINEER_WH TO ROLE RL_DATA_ENGINEER;

-- use the custom role to create schemas within the new database
USE ROLE RL_DATA_ENGINEER;
CREATE SCHEMA RL_SQL_DEMO.EX;
CREATE SCHEMA RL_SQL_DEMO.STG;
CREATE SCHEMA RL_SQL_DEMO.MART;