USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE API INTEGRATION RL_SQL_GIT_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/ReginaLin24')
  API_USER_AUTHENTICATION = (TYPE = SNOWFLAKE_GITHUB_APP)
  ENABLED = TRUE;

-- grant usage on the API integration to all users
GRANT USAGE ON INTEGRATION RL_SQL_GIT_INTEGRATION TO ROLE PUBLIC;


USE ROLE RL_DATA_ENGINEER;
CREATE SCHEMA RL_SQL_DEMO.GOLD;

CREATE OR REPLACE GIT REPOSITORY RL_SQL_REPO
  API_INTEGRATION = RL_SQL_GIT_INTEGRATION
  ORIGIN = 'https://github.com/ReginaLin24/sql-pipeline-demo';

ALTER GIT REPOSITORY RL_SQL_REPO FETCH;

LS @RL_SQL_REPO/branches/main;